---
- name: Create document root for domain configured in host variable
  file:
     path: "/var/www/{{ http_host }}" #create this folder (directory) in node
     state: directory
     owner: root
     group: root
     mode: '0755'

- name: Set up virtualHost
  template:
     src: "templates/apacheconf.j2"
     dest: "/etc/apache2/sites-available/{{ http_conf }}"

- name: Enable site
  command: a2ensite {{ http_conf }}
  notify: restart-apache
